name: Main
on: [push]
jobs:
  mac-test:
    name: Mac Test
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build and test
        run: |
          xcodebuild ${action} -destination ${workspace} -scheme "SWXMLHash OSX"
          xcodebuild ${action} -destination ${workspace} -scheme "SWXMLHash iOS"
          xcodebuild ${action} -destination ${workspace} -scheme "SWXMLHash tvOS"
          xcodebuild ${action} -destination ${workspace} -scheme "SWXMLHash watchOS"
        env:
         workspace: "SWXMLHash.xcworkspace"
         action: "build-for-testing test-without-building"

  linux-test:
    name: Linux Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build and test
        run: |
          swift test


