name: Main
on: [push]
jobs:
  mac-test:
    name: Mac Test
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build and test
        env:
         WORKSPACE: "-workspace SWXMLHash.xcworkspace"
         ACTION: "build-for-testing test-without-building"
        run: |
          xcodebuild $ACTION $WORKSPACE -scheme "SWXMLHash OSX"
          xcodebuild $ACTION $WORKSPACE -scheme "SWXMLHash iOS" -sdk iphonesimulator -destination "OS=12.2,name=iPhone XS"
          xcodebuild $ACTION $WORKSPACE -scheme "SWXMLHash tvOS" -sdk appletvsimulator -destination "name=Apple TV"
          xcodebuild $ACTION $WORKSPACE -scheme "SWXMLHash watchOS" -sdk watchsimulator

  linux-test:
    name: Linux Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build and test
        run: |
          swift test


